<?php
    $formType = DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL;
    //Display options
    $displayOptions = array(
        'fieldsets' => array(
            'entity'    => array(
                'elements'  => array(
                    'path'      => array(
                        'class' => 'input-block-level',
                    ),
                ),
            ),
        ),
    );
?>

 <div id="explorer">

	<div class="explorer_content explorer_content_with_tree">
		<div class="tabMainContent">
			<div class="tabMainContentHolder">
			<?php
                echo $this->formTwb()->openTag($form, $formType);
                $fsEntity   = $form->get('entity');
                $doEntity = $displayOptions['fieldsets']['entity'];
                echo $this->formFieldsetTwb($fsEntity, $formType, $doEntity);

                echo $this->formRowTwb($form->get('act'), $formType);
                echo $this->formRowTwb($form->get('csrf'), $formType);
                echo $this->formFieldsetTwb($form->get('buttons'), $formType);
                echo $this->formTwb()->closeTag();
            ?>
			</div>
		</div>
	</div>
</div>
