<?php
$formType = \DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL;
$form     = $this->form;
echo $this->formTwb($form, $formType);

?>
<? if (count($this->result)) : ?>
    <table id="search_result" border="1">
        <tbody>
            <? foreach ($this->result as $result) : ?>
                    <tr>
                        <td>
                            <a href="<?= $result['url'] ?>" title="<?= $result['title'] ?>"><?= $result['title'] ?></a>
                            <div><?= $result['description'] ?></div>
                            <!-- <div class="url"><a href="<?= $result['url'] ?>" title="<?= $result['title'] ?>"><?= $result['url'] ?></a></div> -->
                        </td>
                        <td class="rate">
                            <?= round(($result['score'] / (float) $this->max_score) * 100, 2) . '%' ?>
                        </td>
                    </tr>
            <? endforeach; ?>
            <tr>
                <td colspan="2">
                    <?= $this->paginator; ?>
                </td>
            </tr>
        </tbody>
    </table>
<? else : ?>
    <p>No results found.</p>
<? endif; ?>
